
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: pin_point_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
        sleep 5 &&

        python manage.py makemigrations &&

        python manage.py migrate &&

        python manage.py shell -c '
          from django.contrib.auth import get_user_model;
          User = get_user_model();
          if not User.objects.filter(username=\"admin\").exists():
              User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin123\");
              print(\"✓ Суперпользователь создан: admin / admin123\");
          else:
              print(\"✓ Суперпользователь уже существует\");
        ' &&

        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data: